[project]
name = "ave"
version = "0.1.0"
description = "AVEs test tasks"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.124.0",
    "phonenumbers>=9.0.20",
    "pydantic-extra-types>=2.10.6",
    "redis>=7.1.0",
    "starlette>=0.50.0",
]
